services:
  emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:582.0.0-emulators
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8681 --project=messaging-go
    ports:
      - "8681:8681"
  ui:
    image: ghcr.io/neoscript/pubsub-emulator-ui:2025.06.08
    ports:
      - "8080:80"
